[package]
name = "bigbytesdb-common-settings"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
async-backtrace = { workspace = true }
chrono-tz = { workspace = true }
dashmap = { workspace = true }
bigbytesdb-common-ast = { workspace = true }
bigbytesdb-common-config = { workspace = true }
bigbytesdb-common-exception = { workspace = true }
bigbytesdb-common-io = { workspace = true }
bigbytesdb-common-meta-app = { workspace = true }
bigbytesdb-common-users = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
sys-info = { workspace = true }

[dev-dependencies]
bigbytesdb-common-base = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
