[package]
name = "bigbytesdb-common-storages-factory"
version = "0.1.0"
edition = "2021"
authors = ["Bigbytesdb Authors <opensource@getbigbytes.com>"]
license = "Apache-2.0"
publish = false

[lib]
doctest = false
test = true

[dependencies]
dashmap = { workspace = true }
bigbytesdb-common-catalog = { workspace = true }
bigbytesdb-common-config = { workspace = true }
bigbytesdb-common-exception = { workspace = true }
bigbytesdb-common-meta-app = { workspace = true }
bigbytesdb-common-storages-delta = { workspace = true }
bigbytesdb-common-storages-fuse = { workspace = true }
bigbytesdb-common-storages-iceberg = { workspace = true }
bigbytesdb-common-storages-memory = { workspace = true }
bigbytesdb-common-storages-null = { workspace = true }
bigbytesdb-common-storages-random = { workspace = true }
bigbytesdb-common-storages-stream = { workspace = true }
bigbytesdb-common-storages-view = { workspace = true }
bigbytesdb-storages-common-index = { workspace = true }

[lints]
workspace = true
