name: "Upload failure Artifacts"
description: "Upload failure Artifacts"
inputs:
  name:
    description: ""
    required: true
runs:
  using: "composite"
  steps:
    - name: pack failure artifacts
      shell: bash
      run: |
        killall -9 bigbytes-query || true
        killall -9 bigbytes-meta || true

        docker ps -a
        mkdir -p .bigbytes/docker/
        docker ps -a --format "{{.Names}}" | while read -r line; do
            docker logs "$line" > .bigbytes/docker/"$line".log
        done

        touch nohup.out
        cp nohup.out .bigbytes/nohup.out

        mkdir -p target
        find -type d -name .bigbytes -print0 | xargs -0 tar -zcf target/failure-${{ inputs.name }}.tar.gz
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: target/failure-${{ inputs.name }}.tar.gz
