[package]
name = "bigbytesdb-common-ast"
version = "0.1.3"
publish = true
description = "SQL parser for Bigbytesdb"
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = "https://github.com/getbigbytes/bigbytesdb/tree/main/src/query/ast"

[lib]
doctest = false

[dependencies]
derive-visitor = { workspace = true }
enum-as-inner = { workspace = true }
ethnum = { workspace = true }
fast-float2 = { workspace = true }
fastrace = { workspace = true }
indent = { workspace = true }
itertools = { workspace = true }
logos = { workspace = true }
nom = { workspace = true }
nom-rule = { workspace = true }
ordered-float = { workspace = true }
percent-encoding = { workspace = true }
pratt = { workspace = true }
pretty_assertions = { workspace = true }
recursive = { workspace = true }
rspack-codespan-reporting = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strsim = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
unindent = { workspace = true }
url = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
goldenfile = { workspace = true }

[[bench]]
name = "bench"
harness = false

[lints]
workspace = true
