[package]
name = "bigbytesdb-common-storages-parquet"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
arrow-array = { workspace = true }
arrow-buffer = { workspace = true }
arrow-schema = { workspace = true }
async-backtrace = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }

bigbytesdb-common-ast = { workspace = true }
bigbytesdb-common-base = { workspace = true }
bigbytesdb-common-catalog = { workspace = true }
bigbytesdb-common-exception = { workspace = true }
bigbytesdb-common-expression = { workspace = true }
bigbytesdb-common-functions = { workspace = true }
bigbytesdb-common-meta-app = { workspace = true }
bigbytesdb-common-metrics = { workspace = true }
bigbytesdb-common-pipeline-core = { workspace = true }
bigbytesdb-common-settings = { workspace = true }
bigbytesdb-common-storage = { workspace = true }
bigbytesdb-storages-common-cache = { workspace = true }
bigbytesdb-storages-common-pruner = { workspace = true }
bigbytesdb-storages-common-stage = { workspace = true }
bigbytesdb-storages-common-table-meta = { workspace = true }
ethnum = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
opendal = { workspace = true }
parquet = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
thrift = { workspace = true }
typetag = { workspace = true }

[lints]
workspace = true
