[package]
name = "bigbytesdb-storages-common-pruner"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
bigbytesdb-common-exception = { workspace = true }
bigbytesdb-common-expression = { workspace = true }
bigbytesdb-common-functions = { workspace = true }
bigbytesdb-storages-common-index = { workspace = true }
bigbytesdb-storages-common-table-meta = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
typetag = { workspace = true }

[lints]
workspace = true
