[package]
name = "bigbytesdb-query"
description = "A real-time Cloud Distributed Query Engine"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[features]
default = ["simd"]
simd = ["bigbytesdb-common-column/simd"]
python-udf = ["arrow-udf-python"]
disable_initial_exec_tls = ["bigbytesdb-common-base/disable_initial_exec_tls"]
jemalloc = ["bigbytesdb-common-storages-system/jemalloc"]
memory-profiling = ["bigbytesdb-common-base/memory-profiling", "bigbytesdb-common-http/memory-profiling"]
storage-hdfs = ["opendal/services-hdfs", "bigbytesdb-common-storage/storage-hdfs"]
io-uring = [
    "bigbytesdb-common-meta-store/io-uring",
]

enable_queries_executor = []

[dependencies]
anyhow = { workspace = true }
arrow-array = { workspace = true }
arrow-buffer = { workspace = true }
arrow-flight = { workspace = true }
arrow-ipc = { workspace = true, features = ["lz4", "zstd"] }
arrow-schema = { workspace = true }
arrow-select = { workspace = true }
arrow-udf-js = { workspace = true }
arrow-udf-python = { workspace = true, optional = true }
arrow-udf-wasm = { workspace = true }
async-backtrace = { workspace = true }
async-channel = { workspace = true }
async-compat = { workspace = true }
async-recursion = { workspace = true }
async-stream = { workspace = true }
async-trait = { workspace = true }
backoff = { workspace = true, features = ["futures", "tokio"] }
backon = { workspace = true }
base64 = { workspace = true }
buf-list = { workspace = true }
bumpalo = { workspace = true }
byte-unit = { workspace = true }
byteorder = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
ctor = { workspace = true }
dashmap = { workspace = true }
bigbytesdb-common-ast = { workspace = true }
bigbytesdb-common-base = { workspace = true }
bigbytesdb-common-cache = { workspace = true }
bigbytesdb-common-catalog = { workspace = true }
bigbytesdb-common-cloud-control = { workspace = true }
bigbytesdb-common-column = { workspace = true }
bigbytesdb-common-config = { workspace = true }
bigbytesdb-common-exception = { workspace = true }
bigbytesdb-common-expression = { workspace = true }
bigbytesdb-common-formats = { workspace = true }
bigbytesdb-common-functions = { workspace = true }
bigbytesdb-common-grpc = { workspace = true }
bigbytesdb-common-hashtable = { workspace = true }
bigbytesdb-common-http = { workspace = true }
bigbytesdb-common-io = { workspace = true }
bigbytesdb-common-license = { workspace = true }
bigbytesdb-common-management = { workspace = true }
bigbytesdb-common-meta-api = { workspace = true }
bigbytesdb-common-meta-app = { workspace = true }
bigbytesdb-common-meta-kvapi = { workspace = true }
bigbytesdb-common-meta-store = { workspace = true }
bigbytesdb-common-meta-types = { workspace = true }
bigbytesdb-common-metrics = { workspace = true }
bigbytesdb-common-openai = { workspace = true }
bigbytesdb-common-pipeline-core = { workspace = true }
bigbytesdb-common-pipeline-sinks = { workspace = true }
bigbytesdb-common-pipeline-sources = { workspace = true }
bigbytesdb-common-pipeline-transforms = { workspace = true }
bigbytesdb-common-script = { workspace = true }
bigbytesdb-common-settings = { workspace = true }
bigbytesdb-common-sql = { workspace = true }
bigbytesdb-common-storage = { workspace = true }
bigbytesdb-common-storages-delta = { workspace = true }
bigbytesdb-common-storages-factory = { workspace = true }
bigbytesdb-common-storages-fuse = { workspace = true }
bigbytesdb-common-storages-hive = { workspace = true }
bigbytesdb-common-storages-iceberg = { workspace = true }
bigbytesdb-common-storages-information-schema = { workspace = true }
bigbytesdb-common-storages-memory = { workspace = true }
bigbytesdb-common-storages-null = { workspace = true }
bigbytesdb-common-storages-orc = { workspace = true }
bigbytesdb-common-storages-parquet = { workspace = true }
bigbytesdb-common-storages-result-cache = { workspace = true }
bigbytesdb-common-storages-stage = { workspace = true }
bigbytesdb-common-storages-stream = { workspace = true }
bigbytesdb-common-storages-system = { workspace = true }
bigbytesdb-common-storages-view = { workspace = true }
bigbytesdb-common-tracing = { workspace = true }
bigbytesdb-common-users = { workspace = true }
bigbytesdb-enterprise-aggregating-index = { workspace = true }
bigbytesdb-enterprise-attach-table = { workspace = true }
bigbytesdb-enterprise-background-service = { workspace = true }
bigbytesdb-enterprise-data-mask-feature = { workspace = true }
bigbytesdb-enterprise-inverted-index = { workspace = true }
bigbytesdb-enterprise-resources-management = { workspace = true }
bigbytesdb-enterprise-stream-handler = { workspace = true }
bigbytesdb-enterprise-vacuum-handler = { workspace = true }
bigbytesdb-enterprise-virtual-column = { workspace = true }
bigbytesdb-storages-common-blocks = { workspace = true }
bigbytesdb-storages-common-cache = { workspace = true }
bigbytesdb-storages-common-index = { workspace = true }
bigbytesdb-storages-common-io = { workspace = true }
bigbytesdb-storages-common-session = { workspace = true }
bigbytesdb-storages-common-table-meta = { workspace = true }
derive-visitor = { workspace = true }
ethnum = { workspace = true }
fastrace = { workspace = true }
flatbuffers = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
headers = { workspace = true }
hex = { workspace = true }
highway = { workspace = true }
http = { workspace = true }
humantime = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
jiff = { workspace = true }
jsonb = { workspace = true }
jwt-simple = { workspace = true }
log = { workspace = true }
lz4 = { workspace = true }
match-template = { workspace = true }
md-5 = { workspace = true }
naive-cityhash = { workspace = true }
num_cpus = { workspace = true }
opendal = { workspace = true }
opensrv-mysql = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
parking_lot = { workspace = true }
parquet = { workspace = true }
paste = { workspace = true }
petgraph = { workspace = true }
pin-project-lite = { workspace = true }
poem = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
recursive = { workspace = true }
redis = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
rustls-pki-types = { workspace = true }
rustyline = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_stacker = { workspace = true }
serde_urlencoded = { workspace = true }
sha2 = { workspace = true }
socket2 = { workspace = true }
sqlx = { workspace = true }
sysinfo = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true, features = ["net"] }
toml = { workspace = true, default-features = false }
tonic = { workspace = true }
typetag = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
walkdir = { workspace = true }
xorf = { workspace = true }

[dev-dependencies]
arrow-cast = { workspace = true }
goldenfile = { workspace = true }
hex = { workspace = true }
hyper-util = { workspace = true }
jwt-simple = { workspace = true }
maplit = { workspace = true }
mysql_async = { workspace = true }
p256 = { workspace = true }
pretty_assertions = { workspace = true }
reqwest = { workspace = true }
temp-env = { workspace = true }
tempfile = { workspace = true }
tower = { workspace = true }
url = { workspace = true }
wiremock = { workspace = true }

[build-dependencies]
bigbytesdb-common-building = { workspace = true }

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = ["match-template", "md-5"]
