[package]
name = "bigbytes-common-storages-orc"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["serde"]

[lib]
doctest = false
test = true

[dependencies]
bigbytes-common-base = { workspace = true }
bigbytes-common-catalog = { workspace = true }
bigbytes-common-exception = { workspace = true }
bigbytes-common-expression = { workspace = true }
bigbytes-common-functions = { workspace = true }
bigbytes-common-meta-app = { workspace = true }
bigbytes-common-pipeline-core = { workspace = true }
bigbytes-common-pipeline-sources = { workspace = true }
bigbytes-common-pipeline-transforms = { workspace = true }
bigbytes-common-storage = { workspace = true }
bigbytes-storages-common-stage = { workspace = true }
bigbytes-storages-common-table-meta = { workspace = true }

arrow-array = { workspace = true }
arrow-schema = { workspace = true, features = ["serde"] }
async-backtrace = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
dashmap = { workspace = true }
futures-util = { workspace = true }
log = { workspace = true }
opendal = { workspace = true }
orc-rust = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
typetag = { workspace = true }

[lints]
workspace = true
