[package]
name = "bigbytesdb-common-storages-result-cache"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
arrow = { workspace = true }
async-backtrace = { workspace = true }
async-trait = { workspace = true }
bigbytesdb-common-catalog = { workspace = true }
bigbytesdb-common-exception = { workspace = true }
bigbytesdb-common-expression = { workspace = true }
bigbytesdb-common-meta-app = { workspace = true }
bigbytesdb-common-meta-kvapi = { workspace = true }
bigbytesdb-common-meta-store = { workspace = true }
bigbytesdb-common-meta-types = { workspace = true }
bigbytesdb-common-pipeline-core = { workspace = true }
bigbytesdb-common-pipeline-sinks = { workspace = true }
bigbytesdb-common-storage = { workspace = true }
bigbytesdb-common-storages-parquet = { workspace = true }
bigbytesdb-storages-common-blocks = { workspace = true }
bigbytesdb-storages-common-table-meta = { workspace = true }
opendal = { workspace = true }
parquet = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }

[lints]
workspace = true
