[package]
name = "bigbytesdb-storages-common-stage"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[dependencies]
bigbytesdb-common-catalog = { workspace = true }
bigbytesdb-common-exception = { workspace = true }
bigbytesdb-common-expression = { workspace = true }
bigbytesdb-common-functions = { workspace = true }
bigbytesdb-common-meta-app = { workspace = true }
serde = { workspace = true }
typetag = { workspace = true }

[lints]
workspace = true
