[package]
name = "bigbytes-storages-common-stage"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[dependencies]
bigbytes-common-catalog = { workspace = true }
bigbytes-common-exception = { workspace = true }
bigbytes-common-expression = { workspace = true }
bigbytes-common-functions = { workspace = true }
bigbytes-common-meta-app = { workspace = true }
serde = { workspace = true }
typetag = { workspace = true }

[lints]
workspace = true
