[package]
name = "bigbytes-common-storages-stage"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
arrow-schema = { workspace = true }
async-backtrace = { workspace = true }
async-trait = { workspace = true }
bstr = { workspace = true }
csv-core = { workspace = true }
bigbytes-common-ast = { workspace = true }
bigbytes-common-base = { workspace = true }
bigbytes-common-catalog = { workspace = true }
bigbytes-common-compress = { workspace = true }
bigbytes-common-config = { workspace = true }
bigbytes-common-exception = { workspace = true }
bigbytes-common-expression = { workspace = true }
bigbytes-common-formats = { workspace = true }
bigbytes-common-functions = { workspace = true }
bigbytes-common-io = { workspace = true }
bigbytes-common-meta-app = { workspace = true }
bigbytes-common-pipeline-core = { workspace = true }
bigbytes-common-pipeline-sources = { workspace = true }
bigbytes-common-pipeline-transforms = { workspace = true }
bigbytes-common-settings = { workspace = true }
bigbytes-common-storage = { workspace = true }
bigbytes-common-storages-orc = { workspace = true }
bigbytes-common-storages-parquet = { workspace = true }
bigbytes-storages-common-stage = { workspace = true }
bigbytes-storages-common-table-meta = { workspace = true }
enum-as-inner = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
opendal = { workspace = true }
parquet = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
typetag = { workspace = true }

[lints]
workspace = true
