[package]
name = "bigbytesdb-common-sql"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[features]
default = []
storage-hdfs = ["bigbytesdb-common-config/storage-hdfs"]

[dependencies]
bigbytesdb-common-ast = { workspace = true }
bigbytesdb-common-base = { workspace = true }
bigbytesdb-common-catalog = { workspace = true }
bigbytesdb-common-compress = { workspace = true }
bigbytesdb-common-config = { workspace = true }
bigbytesdb-common-exception = { workspace = true }
bigbytesdb-common-expression = { workspace = true }
bigbytesdb-common-functions = { workspace = true }
bigbytesdb-common-license = { workspace = true }
bigbytesdb-common-meta-app = { workspace = true }
bigbytesdb-common-meta-types = { workspace = true }
bigbytesdb-common-metrics = { workspace = true }
bigbytesdb-common-pipeline-core = { workspace = true }
bigbytesdb-common-pipeline-transforms = { workspace = true }
bigbytesdb-common-settings = { workspace = true }
bigbytesdb-common-storage = { workspace = true }
bigbytesdb-common-storages-result-cache = { workspace = true }
bigbytesdb-common-storages-view = { workspace = true }
bigbytesdb-common-users = { workspace = true }
bigbytesdb-enterprise-data-mask-feature = { workspace = true }
bigbytesdb-enterprise-hilbert-clustering = { workspace = true }
bigbytesdb-storages-common-cache = { workspace = true }
bigbytesdb-storages-common-io = { workspace = true }
bigbytesdb-storages-common-session = { workspace = true }
bigbytesdb-storages-common-table-meta = { workspace = true }

ahash = { workspace = true, features = ["no-rng"] }
anyhow = { workspace = true }
async-backtrace = { workspace = true }
async-recursion = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
cidr = { workspace = true }
cron = { workspace = true }
ctor = { workspace = true }
dashmap = { workspace = true }
derive-visitor = { workspace = true }
educe = { workspace = true }
enum-as-inner = { workspace = true }
fastrace = { workspace = true }
globiter = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
jsonb = { workspace = true }
log = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
opendal = { workspace = true }
parking_lot = { workspace = true }
prqlc = { workspace = true }
rand = { workspace = true }
recursive = { workspace = true }
regex = { workspace = true }
roaring = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
simsearch = { workspace = true }
tokio = { workspace = true }
unicase = { workspace = true }
url = { workspace = true }

[lints]
workspace = true
