[package]
name = "bigbytesdb-functions-scalar-arithmetic"
version = "0.1.0"
edition = "2021"

[dependencies]
bigbytesdb-common-expression = { workspace = true }
bigbytesdb-functions-scalar-decimal = { workspace = true }
ethnum = { workspace = true }
lexical-core = { workspace = true }
match-template = { workspace = true }
num-traits = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["match-template"]
