[package]
name = "bigbytesdb-functions-scalar-decimal"
version = "0.1.0"
edition = "2021"

[dependencies]
bigbytesdb-common-base = { workspace = true }
bigbytesdb-common-expression = { workspace = true }
ethnum = { workspace = true }
match-template = { workspace = true }
num-traits = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["match-template"]
