[package]
name = "bigbytesdb-common-storages-hive"
version = "0.1.0"
edition = "2021"
authors = ["Bigbytesdb Authors <opensource@getbigbytes.com>"]
license = "Apache-2.0"
publish = false

[lib]
doctest = false
test = true

[dependencies]
async-backtrace = { workspace = true }
async-recursion = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
bigbytesdb-common-base = { workspace = true }
bigbytesdb-common-catalog = { workspace = true }
bigbytesdb-common-config = { workspace = true }
bigbytesdb-common-exception = { workspace = true }
bigbytesdb-common-expression = { workspace = true }
bigbytesdb-common-functions = { workspace = true }
bigbytesdb-common-meta-app = { workspace = true }
bigbytesdb-common-meta-store = { workspace = true }
bigbytesdb-common-meta-types = { workspace = true }
bigbytesdb-common-pipeline-core = { workspace = true }
bigbytesdb-common-pipeline-sources = { workspace = true }
bigbytesdb-common-sql = { workspace = true }
bigbytesdb-common-storage = { workspace = true }
bigbytesdb-common-storages-parquet = { workspace = true }
bigbytesdb-storages-common-pruner = { workspace = true }
bigbytesdb-storages-common-table-meta = { workspace = true }
fastrace = { workspace = true }
faststr = { workspace = true }
futures = { workspace = true }
hive_metastore = { workspace = true }
log = { workspace = true }
opendal = { workspace = true }
parquet = { workspace = true }
recursive = { workspace = true }
serde = { workspace = true }
typetag = { workspace = true }
volo-thrift = { workspace = true }

[lints]
workspace = true
