[package]
name = "bigbytesdb-common-pipeline-transforms"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
async-backtrace = { workspace = true }
async-trait = { workspace = true }
bigbytesdb-common-base = { workspace = true }
bigbytesdb-common-exception = { workspace = true }
bigbytesdb-common-expression = { workspace = true }
bigbytesdb-common-pipeline-core = { workspace = true }
jsonb = { workspace = true }
log = { workspace = true }
match-template = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
typetag = { workspace = true }

[dev-dependencies]
itertools = { workspace = true }
rand = { workspace = true }

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = ["match-template"]
