[package]
name = "bigbytes-common-storages-fuse"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]

bigbytes-common-base = { workspace = true }
bigbytes-common-catalog = { workspace = true }
bigbytes-common-exception = { workspace = true }
bigbytes-common-expression = { workspace = true }
bigbytes-common-functions = { workspace = true }
bigbytes-common-hashtable = { workspace = true }
bigbytes-common-io = { workspace = true }
bigbytes-common-license = { workspace = true }
bigbytes-common-meta-app = { workspace = true }
bigbytes-common-meta-types = { workspace = true }
bigbytes-common-metrics = { workspace = true }
bigbytes-common-native = { workspace = true }
bigbytes-common-pipeline-core = { workspace = true }
bigbytes-common-pipeline-sinks = { workspace = true }
bigbytes-common-pipeline-sources = { workspace = true }
bigbytes-common-pipeline-transforms = { workspace = true }
bigbytes-common-sql = { workspace = true }
bigbytes-common-storage = { workspace = true }
bigbytes-common-users = { workspace = true }
bigbytes-enterprise-fail-safe = { workspace = true }
bigbytes-storages-common-blocks = { workspace = true }
bigbytes-storages-common-cache = { workspace = true }
bigbytes-storages-common-index = { workspace = true }
bigbytes-storages-common-io = { workspace = true }
bigbytes-storages-common-pruner = { workspace = true }
bigbytes-storages-common-session = { workspace = true }
bigbytes-storages-common-table-meta = { workspace = true }

ahash = { workspace = true }
arrow = { workspace = true }
arrow-array = { workspace = true }
arrow-ipc = { workspace = true, features = ["lz4", "zstd"] }
arrow-schema = { workspace = true }
async-backtrace = { workspace = true }
async-channel = { workspace = true }
async-trait = { workspace = true }
backoff = { workspace = true, features = ["futures", "tokio"] }
bytes = { workspace = true }
chrono = { workspace = true }
enum-as-inner = { workspace = true }
fastrace = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
jsonb = { workspace = true }
log = { workspace = true }
opendal = { workspace = true }
parking_lot = { workspace = true }
parquet = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
siphasher = { workspace = true }
tantivy = { workspace = true }
tantivy-common = { workspace = true }
tantivy-fst = { workspace = true }
tantivy-jieba = { workspace = true }
thrift = { workspace = true }
typetag = { workspace = true }
uuid = { workspace = true }
xorf = { workspace = true, default-features = false, features = ["binary-fuse"] }

[lints]
workspace = true
