[package]
name = "bigbytesdb-functions-scalar-geo"
version = "0.1.0"
edition = "2021"

[dependencies]
bigbytesdb-common-exception = { workspace = true }
bigbytesdb-common-expression = { workspace = true }
bigbytesdb-common-io = { workspace = true }
geo = { workspace = true }
geohash = { workspace = true }
geozero = { workspace = true }
h3o = { workspace = true }
hex = { workspace = true }
jsonb = { workspace = true }
num-traits = { workspace = true }
once_cell = { workspace = true }
proj4rs = { workspace = true }
