[package]
name = "bigbytesdb-common-storages-view"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
async-trait = { workspace = true }
bigbytesdb-common-catalog = { workspace = true }
bigbytesdb-common-exception = { workspace = true }
bigbytesdb-common-meta-app = { workspace = true }

[build-dependencies]

[lints]
workspace = true
