[package]
name = "bigbytesdb-common-storages-null"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
async-backtrace = { workspace = true }
async-trait = { workspace = true }
bigbytesdb-common-catalog = { workspace = true }
bigbytesdb-common-exception = { workspace = true }
bigbytesdb-common-expression = { workspace = true }
bigbytesdb-common-meta-app = { workspace = true }
bigbytesdb-common-pipeline-core = { workspace = true }
bigbytesdb-common-pipeline-sinks = { workspace = true }
bigbytesdb-common-pipeline-sources = { workspace = true }

[lints]
workspace = true
