[package]
name = "bigbytes-common-storages-system"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[features]
jemalloc = ["bigbytes-common-base/jemalloc", "tikv-jemalloc-ctl"]

[dependencies]
async-backtrace = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
bigbytes-common-ast = { workspace = true }
bigbytes-common-base = { workspace = true }
bigbytes-common-catalog = { workspace = true }
bigbytes-common-cloud-control = { workspace = true }
bigbytes-common-config = { workspace = true }
bigbytes-common-exception = { workspace = true }
bigbytes-common-expression = { workspace = true }
bigbytes-common-functions = { workspace = true }
bigbytes-common-management = { workspace = true }
bigbytes-common-meta-api = { workspace = true }
bigbytes-common-meta-app = { workspace = true }
bigbytes-common-meta-types = { workspace = true }
bigbytes-common-metrics = { workspace = true }
bigbytes-common-pipeline-core = { workspace = true }
bigbytes-common-pipeline-sources = { workspace = true }
bigbytes-common-sql = { workspace = true }
bigbytes-common-storage = { workspace = true }
bigbytes-common-storages-fuse = { workspace = true }
bigbytes-common-storages-result-cache = { workspace = true }
bigbytes-common-storages-stream = { workspace = true }
bigbytes-common-storages-view = { workspace = true }
bigbytes-common-users = { workspace = true }
bigbytes-storages-common-cache = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
jiff = { workspace = true }
jsonb = { workspace = true }
log = { workspace = true }
once_cell = { workspace = true }
opendal = { workspace = true }
parking_lot = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_repr = { workspace = true }
snailquote = { workspace = true }
tikv-jemalloc-ctl = { workspace = true, optional = true }
typetag = { workspace = true }

[build-dependencies]
bigbytes-common-building = { workspace = true }

[lints]
workspace = true
