apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bigbytesdb-metaverifier
    app.kubernetes.io/name: bigbytesdb-metaverifier
  name: bigbytesdb-metaverifier
  namespace: bigbytesdb
spec:
  containers:
    - image: k3d-registry.localhost:5111/bigbytesdb-metaverifier:meta-chaos
      imagePullPolicy: Always
      name: bigbytesdb-metaverifier
      resources: {}
      env:
        - name: CLIENT
          value: "10"
        - name: NUMBER
          value: "15000"
        - name: GRPC_ADDRESS
          value: "test-bigbytesdb-meta-0.test-bigbytesdb-meta.bigbytesdb.svc.cluster.local:9191,test-bigbytesdb-meta-1.test-bigbytesdb-meta.bigbytesdb.svc.cluster.local:9191,test-bigbytesdb-meta-2.test-bigbytesdb-meta.bigbytesdb.svc.cluster.local:9191"
      command: [ "/start-verifier.sh"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
