[package]
name = "bigbytesdb-storages-common-session"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[dependencies]
bigbytesdb-common-exception = { workspace = true }
bigbytesdb-common-meta-app = { workspace = true }
bigbytesdb-common-meta-types = { workspace = true }
bigbytesdb-common-storage = { workspace = true }
bigbytesdb-storages-common-blocks = { workspace = true }
bigbytesdb-storages-common-table-meta = { workspace = true }

parking_lot = { workspace = true }
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true }

[lints]
workspace = true
