[package]
name = "bigbytes-common-storages-stream"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
async-backtrace = { workspace = true }
async-trait = { workspace = true }
bigbytes-common-base = { workspace = true }
bigbytes-common-catalog = { workspace = true }
bigbytes-common-exception = { workspace = true }
bigbytes-common-expression = { workspace = true }
bigbytes-common-meta-app = { workspace = true }
bigbytes-common-pipeline-core = { workspace = true }
bigbytes-common-pipeline-sources = { workspace = true }
bigbytes-common-sql = { workspace = true }
bigbytes-common-storages-fuse = { workspace = true }
bigbytes-storages-common-table-meta = { workspace = true }
fastrace = { workspace = true }
futures = { workspace = true }
log = { workspace = true }

[build-dependencies]

[lints]
workspace = true
