[package]
name = "bigbytes-common-pipeline-core"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
async-backtrace = { workspace = true }
async-trait = { workspace = true }
bigbytes-common-base = { workspace = true }
bigbytes-common-exception = { workspace = true }
bigbytes-common-expression = { workspace = true }
fastrace = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
petgraph = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
serde = { workspace = true }
tokio = { workspace = true }
typetag = { workspace = true }

[lints]
workspace = true
