name: "Upload Artifacts"
description: "Upload build Result Binaries"
inputs:
  sha:
    description: "git sha"
    required: true
  target:
    description: ""
    required: true
  path:
    description: "default to ./target/${BUILD_TARGET}/${BUILD_PROFILE}/"
    required: false
    default: ""
  category:
    description: "default/hdfs"
    required: false
    default: default
runs:
  using: "composite"
  steps:
    - name: Get Upload Info
      id: info
      shell: bash
      run: |
        if [[ -z "${{ inputs.path }}" ]]; then
          upload_path="./target/${{ inputs.target }}/${{ env.BUILD_PROFILE }}"
        else
          upload_path="${{ inputs.path }}"
        fi
        ls -lh ${upload_path}
        echo "path=${upload_path}" >> $GITHUB_OUTPUT

    - name: Upload artifact to github
      if: env.RUNNER_PROVIDER == 'github'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.BUILD_PROFILE }}-${{ inputs.sha }}-${{ inputs.target }}-${{ inputs.category }}
        path: ${{ steps.info.outputs.path }}/bigbytes-*

    - name: Upload artifacts to s3
      if: env.RUNNER_PROVIDER == 'aws'
      shell: bash
      run: |
        echo "### artifacts 🚀" >> $GITHUB_STEP_SUMMARY
        aws s3 sync ./target/${{ inputs.target }}/${{ env.BUILD_PROFILE }}/ \
          s3://bigbytes-ci/${{ env.BUILD_PROFILE }}/${{ inputs.sha }}/${{ inputs.target }}/${{ inputs.category }}/ \
          --exclude "*" --include "bigbytes-*" --no-progress
        artifacts="meta,query,query.debug"
        for artifact in ${artifacts//,/ }; do
          if [[ -f ./target/${{ inputs.target }}/${{ env.BUILD_PROFILE }}/bigbytes-${artifact} ]]; then
            url=$(aws s3 presign s3://bigbytes-ci/${{ env.BUILD_PROFILE }}/${{ inputs.sha }}/${{ inputs.target }}/${{ inputs.category }}/bigbytes-${artifact} --expires-in 21600)
            echo "- [${artifact}](${url})" >> $GITHUB_STEP_SUMMARY
          fi
        done

    - name: Upload artifact to gcs
      if: env.RUNNER_PROVIDER == 'gcp'
      shell: bash
      run: |
        gcloud config set storage/parallel_composite_upload_enabled False
        gcloud storage cp --quiet --recursive ./target/${{ inputs.target }}/${{ env.BUILD_PROFILE }}/bigbytes-* \
          gs://bigbytes-ci/${{ env.BUILD_PROFILE }}/${{ inputs.sha }}/${{ inputs.target }}/${{ inputs.category }}/
