[package]
name = "bigbytes-enterprise-resources-management"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
async-trait = { workspace = true }
bigbytes-common-base = { workspace = true }
bigbytes-common-config = { workspace = true }
bigbytes-common-exception = { workspace = true }
bigbytes-common-management = { workspace = true }
bigbytes-common-meta-types = { workspace = true }

[build-dependencies]

[lints]
workspace = true
