[package]
name = "bigbytes-enterprise-storage-quota"

authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
version = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
async-trait = { workspace = true }
bigbytes-common-base = { workspace = true }
bigbytes-common-exception = { workspace = true }
bigbytes-common-license = { workspace = true }

[build-dependencies]

[lints]
workspace = true
