[package]
name = "bigbytes-common-pipeline-sinks"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
async-backtrace = { workspace = true }
async-channel = { workspace = true }
async-trait = { workspace = true }
bigbytes-common-base = { workspace = true }
bigbytes-common-exception = { workspace = true }
bigbytes-common-expression = { workspace = true }
bigbytes-common-pipeline-core = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[lints]
workspace = true
