name: "Upload meta containers failure Artifacts"
description: "Upload meta containers Artifacts"
inputs:
  name:
    description: ""
    required: true
runs:
  using: "composite"
  steps:
    - name: pack failure artifacts
      shell: bash
      run: |
        mkdir -p logs
        for name in "test-bigbytes-meta-0" "test-bigbytes-meta-1" "test-bigbytes-meta-2" "bigbytes-metaverifier"
        do
          echo "cat logs of $name"
          kubectl exec -i $name -n bigbytes -- /cat-logs.sh > logs/$name.log
        done
        tar -zcf logs/failure-${{ inputs.name }}.tar.gz logs/*
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: logs/failure-${{ inputs.name }}.tar.gz
