[package]
name = "bigbytes-common-storages-iceberg"
version = { workspace = true }
edition = "2021"
authors = ["Bigbytes Authors <opensource@getbigbytes.com>"]
license = "Apache-2.0"
publish = false

[dependencies]
arrow-schema = { workspace = true }
async-backtrace = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
bigbytes-common-base = { workspace = true }
bigbytes-common-catalog = { workspace = true }
bigbytes-common-config = { workspace = true }
bigbytes-common-exception = { workspace = true }
bigbytes-common-expression = { workspace = true }
bigbytes-common-meta-app = { workspace = true }
bigbytes-common-meta-store = { workspace = true }
bigbytes-common-meta-types = { workspace = true }
bigbytes-common-pipeline-core = { workspace = true }
bigbytes-common-storages-parquet = { workspace = true }
bigbytes-storages-common-table-meta = { workspace = true }
fastrace = { workspace = true }
futures = { workspace = true }
iceberg = { workspace = true }
iceberg-catalog-glue = { workspace = true }
iceberg-catalog-hms = { workspace = true }
iceberg-catalog-rest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
typetag = { workspace = true }

[lints]
workspace = true
