[package]
name = "bigbytes-functions-scalar-datetime"
version = "0.1.0"
edition = "2021"

[dependencies]
bigbytes-common-column = { workspace = true }
bigbytes-common-exception = { workspace = true }
bigbytes-common-expression = { workspace = true }
dtparse = { workspace = true }
jiff = { workspace = true }
num-traits = { workspace = true }
