[package]
name = "bigbytesdb-functions-scalar-datetime"
version = "0.1.0"
edition = "2021"

[dependencies]
bigbytesdb-common-column = { workspace = true }
bigbytesdb-common-exception = { workspace = true }
bigbytesdb-common-expression = { workspace = true }
dtparse = { workspace = true }
jiff = { workspace = true }
num-traits = { workspace = true }
