# Usage:
# bigbytes-query -c bigbytes_query_config_spec.toml

[query]
max_active_sessions = 256
shutdown_wait_timeout_ms = 5000

# For flight rpc.
flight_api_address = "0.0.0.0:9093"

# Bigbytes Query http address.
# For admin RESET API.
admin_api_address = "0.0.0.0:8083"

# Bigbytes Query metrics RESET API.
metric_api_address = "0.0.0.0:7073"

# Bigbytes Query MySQL Handler.
mysql_handler_host = "0.0.0.0"
mysql_handler_port = 3309


# Bigbytes Query ClickHouse Handler.
clickhouse_http_handler_host = "0.0.0.0"
clickhouse_http_handler_port = 8127

# Bigbytes Query HTTP Handler.
http_handler_host = "0.0.0.0"
http_handler_port = 8003

# Bigbytes Query FlightSQL Handler.
flight_sql_handler_host = "0.0.0.0"
flight_sql_handler_port = 8903

tenant_id = "test_tenant"
cluster_id = "test_cluster"

table_engine_memory_enabled = true
default_storage_format = 'parquet'
default_compression = 'zstd'

[[query.users]]
name = "root"
auth_type = "no_password"

[[query.users]]
name = "default"
auth_type = "no_password"

# This for test
[[query.udfs]]
name = "ping"
definition = "CREATE FUNCTION ping(STRING) RETURNS STRING LANGUAGE python HANDLER = 'ping' ADDRESS = 'http://0.0.0.0:8815'"

[log]

[log.file]
level = "INFO"
format = "text"
dir = "./.bigbytes/logs_3"
prefix_filter = ""

[log.structlog]
on = true
dir = "./.bigbytes/structlog_3"

[meta]
# It is a list of `grpc_api_advertise_host:<grpc-api-port>` of bigbytes-meta config
endpoints = ["0.0.0.0:9191"]
username = "root"
password = "root"
client_timeout_in_second = 60
auto_sync_interval = 60

# Storage config.
[storage]
# fs | s3 | azblob | obs | oss
type = "fs"

# Set a local folder to store your data.
# Comment out this block if you're NOT using local file system as storage.
[storage.fs]
data_path = "./.bigbytes/stateless_test_data"

# Cache config.
[cache]
# Type of storage to keep the table data cache
#
# available options: [none|disk]
# default is "none", which disable table data cache
# use "disk" to enabled disk cache
data_cache_storage = "none"

[cache.disk]
# cache path
path = "./.bigbytes/_cache"
# max bytes of cached data 20G
max_bytes = 21474836480
