[package]
name = "bigbytesdb-storages-common-blocks"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
bigbytesdb-common-exception = { workspace = true }
bigbytesdb-common-expression = { workspace = true }
bigbytesdb-storages-common-table-meta = { workspace = true }
parking_lot = { workspace = true }
parquet = { workspace = true }

[build-dependencies]

[lints]
workspace = true
